services:
  web-rnc-oficial:  # Cambiado a minúsculas
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-rnc-oficial  # Cambiado a minúsculas
    ports:
      - "8484:80"
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge